### ISSUE TITLE
Can Mage and WP be on same server?

### ISSUE THREAD

**Issue by gety9** [stuntcoders/stunt_mage_wprest#6]
Guys hi,

I am interested in your extension. To use it can Mage and WP be on same server?
Or are separate servers required?

**Comment by iodic** [comment]
Hi,

Thanks for your interest. Both WP and Magento can be on the same server. You need to supply the WP REST endpoint URL so the location is not really an issue.

I will close the issue and please let us know if you run into issues with the module.
